<?php

/**
 * @file
 * Contains social_auth_map_name.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function social_auth_map_name_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the social_auth_map_name module.
    case 'help.page.social_auth_map_name':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Maps first name and last name from social login to Drupal user account.') . '</p>';
      return $output;

    default:
  }
}
